name: Update Cheats list

on:
  workflow_dispatch:
  push:
    paths:
      - 'CHT/*.cht'
      - '.github/workflows/list_cheats.yml'
      
jobs:
  List-cheats:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get short SHA
      id: slug
      run: echo "::set-output name=chtcount::$(find CHT -name "*.cht" | wc -l)"

    
    - name: Update Cheats list
      run: |
          cd CHT
          echo game count /ID ${{ steps.slug.outputs.chtcount }} >> ../cheat_list.TSV
          head -n1 -q *.cht | tr -d \" >> ../cheat_list.TSV
          cd ..
          sed -i 's/\/ID/\t/' cheat_list.TSV

    - uses: EndBug/add-and-commit@v7
      if: github.ref == 'refs/heads/main'
      with:
        default_author: github_actions
        message: 'Update Widescreen cheat list'
