name: Update Cheats list

on:
  workflow_dispatch:
  push:
    paths:
      - 'CHT/*.cht'
      - '.github/workflows/list_cheats.yml'
      
jobs:
  List-cheats:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get short SHA
      id: slug
      run: echo "::set-output name=chtcount::$(find CHT -name "*.cht" | wc -l)"

    
    - name: Update Cheats list
      run: |
          cd CHT
          echo game count\|${{ steps.slug.outputs.chtcount }} > ../cheat_list.MD
          echo ------------- \| --------------- \| >> ../cheat_list.MD
          head -n1 -q *.cht | tr -d \" >> ../temp.MD
          cd ..
          sed -i 's/\/ID/ \| /' temp.MD
          sort temp.MD >>cheat_list.MD
          rm temp.MD

    - uses: EndBug/add-and-commit@v9
      if: github.ref == 'refs/heads/main'
      with:
        default_author: github_actions
        message: 'Update Widescreen cheat list'
#        commit: '--amend'
