name: Quality Control

on:
  workflow_dispatch:
  push:
    paths:
      - 'CHT/*.cht'
      - '.github/workflows/QualityControl.yml'
      
jobs:
  List-cheats:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get short SHA
      id: slug
      run: echo "::set-output name=chtcount::$(find CHT -name "*.cht" | wc -l)"

    
    - name: Run QualityControl
      run: |
          chmod +x ./QualityControl.sh
          ./QualityControl.sh
