name: Repack widescreen hacks
on:
  workflow_dispatch:
  push:
    paths:
      - '**.cht'

jobs:
  check-binaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: append credits to all cheats
        run: |
          chmod +x ./Append.sh
          ./Append.sh

      - name: zip cheats
        run: |
          zip widescreen_hacks CHT/*

      - name: create release body
        run: |
            echo "- [__List of supported games__](https://github.com/PS2-Widescreen/OPL-Widescreen-Cheats/blob/main/cheat_list.MD)">latest_changes.log
            echo "![Available cheats count](https://img.shields.io/github/directory-file-count/PS2-Widescreen/OPL-Widescreen-Cheats/CHT?color=gree&extension=cht&label=Available%20cheats&type=file)">>latest_changes.log
            echo "![GitHub release (latest by date)](https://img.shields.io/github/downloads/PS2-Widescreen/OPL-Widescreen-Cheats/Latest/total?label=Downloads)">>latest_changes.log

      - name: Upload artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: WIDESCREEN
          path: |
             widescreen_hacks*.zip

      - name: delete previous tag/release
        if: (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: Latest
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy release
        uses: softprops/action-gh-release@v1
        if: (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          fail_on_unmatched_files: true
          files: |
               widescreen_hacks*.zip
          name: "Latest Package"
          tag_name: "Latest"
          body_path: 'latest_changes.log'
          prerelease: false
