name: Repack widescreen hacks
on:
  workflow_dispatch:
  push:
    paths:
      - '**.cht'

jobs:
  check-binaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: zip cheats
        run: |
          
          zip widescreen_hacks CHT/*
    
      - name: Upload artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: WIDESCREEN
          path: |
             widescreen_hacks*.zip

      - name: Create pre-release
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "Latest"
          prerelease: false
          title: "Latest Version"
          files: |
                widescreen_hacks*.zip
